data=read.csv("Heart Failure Clinical Records.csv")
View(data)
model=lm(age~anaemia+diabetes,data=data)
summary(model)
model_A=lm(diabetes~smoking+high_blood_pressure,data=data)
summary(model_A)
model_B=lm(platelets~sex+time,data=data)
summary(model_B)
model_C=lm(age~.,data=data)
summary(model_C)
